require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/{bundle,rails,rake}"
    - "db/migrate/*"
    - "vendor/**/*"
    - "**/spec_helper.rb"

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 80

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
