services:
  db:
    image: mysql:8.0.30
    user: mysql
    command: >-
      mysqld
      & chmod 555 /docker-entrypoint-initdb.d/00_create-test-db.sh
    healthcheck:
      test: mysqladmin ping -h db -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}
      interval: 1s
      start_period: 50s
    restart: always
    volumes:
      - mysql-datadir:/var/lib/mysql
      - type: bind
        source: ./.docker/db/conf.d/docker.cnf
        target: /etc/mysql/conf.d/docker.cnf
      - type: bind
        source: ./.docker/db/initdb.d
        target: /docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.docker/db/environment/mysql-variables.env
    ports:
      - ${DB_PORT:-3306}:3306
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - RUBY_IMAGE_TAG=3.1.2
        - RUBYGEMS_VERSION=3.3.22
      secrets:
        - github-pkg-cred
    restart: always
    volumes:
      - .:/${COMPOSE_PROJECT_NAME}
      - gem-home:/usr/local/bundle
      - puma-socket:/${COMPOSE_PROJECT_NAME}/tmp/sockets
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - XDG_CONFIG_DIRS=/${COMPOSE_PROJECT_NAME}
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./.docker/web
      args:
        - NGINX_IMAGE_TAG=1.22.0
    restart: always
    volumes:
      - puma-socket:/${COMPOSE_PROJECT_NAME}/tmp/sockets
      - type: bind
        source: ./.docker/web/conf.d/myapp.conf
        target: /etc/nginx/conf.d/myapp.conf
    ports:
      - ${WEB_PORT:-80}:80
    depends_on:
      - api
secrets:
  github-pkg-cred:
    file: ./.docker/api/secrets/github-pkg-cred.txt
volumes:
  mysql-datadir:
  gem-home:
  puma-socket:
