services:
  db:
    image: mysql:${MYSQL_IMAGE_TAG:?}
    user: mysql
    command: >-
      mysqld
      & chmod 555 /docker-entrypoint-initdb.d/00_create-test-db.sh
    healthcheck:
      test: mysqladmin ping -h db -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}
      interval: 1s
      start_period: 50s
    restart: always
    volumes:
      - mysql-datadir:/var/lib/mysql
      - type: bind
        source: ./.docker/db/conf.d/docker.cnf
        target: /etc/mysql/conf.d/docker.cnf
      - type: bind
        source: ./.docker/db/initdb.d
        target: /docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ${MYSQL_ENV_PATH:?}
    ports:
      - ${DB_PORT:?}:3306
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME:?}
        - RUBY_IMAGE_TAG=${RUBY_IMAGE_TAG:?}
        - RUBYGEMS_VERSION=${RUBYGEMS_VERSION:?}
        - USER_NAME=${API_USER_NAME:?}
      secrets:
        - github-pkg-cred
    restart: always
    volumes:
      - .:/${COMPOSE_PROJECT_NAME:?}
      - gem-home:/usr/local/bundle
      - puma-socket:${API_SOCKETS_PATH:?}
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - XDG_CONFIG_DIRS=/${COMPOSE_PROJECT_NAME:?}
    env_file:
      - ${MYSQL_ENV_PATH:?}
    ports:
      - ${API_PORT:?}:3000
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./.docker/web
      args:
        - NGINX_IMAGE_TAG=${NGINX_IMAGE_TAG:?}
    restart: always
    volumes:
      - puma-socket:${API_SOCKETS_PATH:?}
      - type: bind
        source: ./.docker/web/nginx/conf.d/myapp.conf
        target: /etc/nginx/conf.d/myapp.conf
        read_only: true
      - type: bind
        source: ./.docker/web/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - ${WEB_PORT:?}:80
    depends_on:
      - api
secrets:
  github-pkg-cred:
    file: ./.docker/api/secrets/github-pkg-cred.txt
volumes:
  mysql-datadir:
  gem-home:
  puma-socket:
