default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: db

development:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["MYSQL_TEST_DATABASE"] %>

# production:
#   <<: *default
#   database: project_name_production
#   username: db_user_name
#   password: <%= ENV["PROJECT_NAME_DATABASE_PASSWORD"] %>
