services:
  api:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - bashlog:/home/ruby/bashlog
      - gh-config:/home/node/.config/gh
      - vscode-extensions:/home/ruby/.vscode-server/extensions
      - yard-gem-index:/home/ruby/.yard/gem_index
    command: bash -c "while sleep 1000; do :; done"
volumes:
  bashlog:
  gh-config:
  vscode-extensions:
  yard-gem-index:
