group :development, :test do
  gem "rspec-rails", "~> 3.9"

  gem "factory_bot_rails", "~> 5.0"

  gem "guard"
  gem "guard-rspec", require: false
end

group :development do
  gem "lefthook"

  gem "rubocop", "~> 1.31", require: false
  gem "rubocop-performance", "~> 1.14", require: false
  gem "rubocop-rails", "~> 2.15", require: false
  gem "rubocop-rspec", "~> 2.11", require: false

  source "https://rubygems.pkg.github.com/p-manbrown" do
    gem "my_git-lint"
  end
end
