group :development, :test do
  gem 'rspec-rails', '~> 6.0.0'

  gem "factory_bot_rails", "~> 5.0"

  gem "guard"
  gem "guard-rspec", require: false
end

group :development do
  gem "lefthook", "~> 1.2", require: false

  gem "mdl", "~> 1.2", require: false

  gem "rubocop", "~> 1.39", require: false
  gem "rubocop-performance", "~> 1.15", require: false
  gem "rubocop-rails", "~> 2.17", require: false
  gem "rubocop-rspec", "~> 2.15", require: false

  source "https://rubygems.pkg.github.com/p-manbrown" do
    gem "my_git-lint", require: false
  end
end
